# Generated by Django 3.0.2 on 2020-01-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_auto_20200110_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=500)),
                ('csv', models.ImageField(upload_to='term_files')),
            ],
        ),
    ]
