# Generated by Django 3.1.dev20200211193912 on 2020-03-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0004_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='../media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='csv',
            field=models.FileField(upload_to='hate_speech'),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, default=None, to='smart.Category'),
        ),
    ]
