# Generated by Django 3.1.dev20200211193912 on 2020-03-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0005_auto_20200322_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('misogynistic', 'misogynistic'), ('racist', 'racist'), ('homophobic', 'homophobic')], max_length=200),
        ),
    ]
