# Generated by Django 3.1.dev20200211193912 on 2020-04-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0006_auto_20200324_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='date', null=True)),
            ],
        ),
    ]
